//
// Copyright (c) 2025 Mohammad Nejati
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at https://www.boost.org/LICENSE_1_0.txt)
//
// Official repository: https://github.com/boostorg/http
//


[#reference]
= Reference

[width=100%]
|===
3+| *HTTP* | *RFC*

| *Types (1/2)*

cpp:boost::http::application[application]

cpp:boost::http::datastore[datastore]

cpp:boost::http::fields[fields]

cpp:boost::http::fields_base[fields_base]

cpp:boost::http::file[file]

cpp:boost::http::header_limits[header_limits]

cpp:boost::http::message_base[message_base]

cpp:boost::http::metadata[metadata]

cpp:boost::http::parser[parser]

cpp:boost::http::polystore[polystore]

cpp:boost::http::request[request]

cpp:boost::http::request_base[request_base]

cpp:boost::http::request_parser[request_parser]

cpp:boost::http::response[response]

cpp:boost::http::response_base[response_base]

cpp:boost::http::response_parser[response_parser]

| **Types (2/2)**

cpp:boost::http::parser_config[parser_config]

cpp:boost::http::parser_config_impl[parser_config_impl]

cpp:boost::http::serializer[serializer]

cpp:boost::http::serializer_config[serializer_config]

cpp:boost::http::serializer_config_impl[serializer_config_impl]

cpp:boost::http::static_request[static_request]

cpp:boost::http::static_response[static_response]

cpp:boost::http::string_body[string_body]

**Type Aliases**

cpp:boost::http::shared_parser_config[shared_parser_config]

cpp:boost::http::shared_serializer_config[shared_serializer_config]

**Functions**

cpp:boost::http::combine_field_values[combine_field_values]

cpp:boost::http::install_parser_service[install_parser_service]

cpp:boost::http::install_serializer_service[install_serializer_service]

cpp:boost::http::int_to_status[int_to_status]

cpp:boost::http::invoke[invoke]

cpp:boost::http::make_parser_config[make_parser_config]

cpp:boost::http::make_serializer_config[make_serializer_config]

cpp:boost::http::obsolete_reason[obsolete_reason]

cpp:boost::http::string_to_field[string_to_field]

cpp:boost::http::string_to_method[string_to_method]

cpp:boost::http::to_status_class[to_status_class]

cpp:boost::http::to_string[to_string]

| **Constants**

cpp:boost::http::condition[condition]

cpp:boost::http::content_coding[content_coding]

cpp:boost::http::error[error]

cpp:boost::http::field[field]

cpp:boost::http::file_mode[file_mode]

cpp:boost::http::method[method]

cpp:boost::http::payload[payload]

cpp:boost::http::status[status]

cpp:boost::http::status_class[status_class]

cpp:boost::http::version[version]

| **Grammar Rules**

cpp:boost::http::list_rule[list_rule]

cpp:boost::http::media_type_rule[media_type_rule]

cpp:boost::http::parameter_rule[parameter_rule]

cpp:boost::http::quoted_token_rule[quoted_token_rule]

cpp:boost::http::token_rule[token_rule]

cpp:boost::http::upgrade_protocol_rule[upgrade_protocol_rule]

cpp:boost::http::upgrade_rule[upgrade_rule]

**Types**

cpp:boost::http::media_type[media_type]

cpp:boost::http::mime_type[mime_type]

cpp:boost::http::parameter[parameter]

cpp:boost::http::quoted_token_view[quoted_token_view]

cpp:boost::http::upgrade_protocol[upgrade_protocol]

**Constants**

cpp:boost::http::tchars[tchars]

|===

[width=100%]
|===
2+| *Server*

| **Types (1/2)**

cpp:boost::http::byte_range[byte_range]

cpp:boost::http::cors[cors]

cpp:boost::http::cors_options[cors_options]

cpp:boost::http::dotfiles_policy[dotfiles_policy]

cpp:boost::http::etag_options[etag_options]

cpp:boost::http::range_result[range_result]

cpp:boost::http::range_result_type[range_result_type]

cpp:boost::http::route_params[route_params]

cpp:boost::http::route_result[route_result]

cpp:boost::http::route_task[route_task]

cpp:boost::http::route_what[route_what]

cpp:boost::http::router[router]

cpp:boost::http::router_options[router_options]

| **Types (2/2)**

cpp:boost::http::send_file_info[send_file_info]

cpp:boost::http::send_file_options[send_file_options]

cpp:boost::http::send_file_result[send_file_result]

cpp:boost::http::serve_static[serve_static]

cpp:boost::http::serve_static_options[serve_static_options]

**Functions**

cpp:boost::http::encode_url[encode_url]

cpp:boost::http::escape_html[escape_html]

cpp:boost::http::etag[etag]

cpp:boost::http::format_http_date[format_http_date]

cpp:boost::http::is_fresh[is_fresh]

cpp:boost::http::parse_range[parse_range]

cpp:boost::http::route_error[route_error]

cpp:boost::http::send_file_init[send_file_init]

**Constants**

cpp:boost::http::route_close[route_close]

cpp:boost::http::route_done[route_done]

cpp:boost::http::route_next[route_next]

cpp:boost::http::route_next_route[route_next_route]

**Namespace `mime_types`**

cpp:boost::http::mime_types::charset[charset]

cpp:boost::http::mime_types::content_type[content_type]

cpp:boost::http::mime_types::extension[extension]

cpp:boost::http::mime_types::lookup[lookup]

**Namespace `statuses`**

cpp:boost::http::statuses::is_empty[is_empty]

cpp:boost::http::statuses::is_redirect[is_redirect]

cpp:boost::http::statuses::is_retry[is_retry]

|===

[width=100%]
|===
3+| *ZLib* | *Brotli*

| **Types**

cpp:boost::http::zlib::deflate_service[deflate_service]

cpp:boost::http::zlib::inflate_service[inflate_service]

cpp:boost::http::zlib::stream[stream]

**Functions**

cpp:boost::http::zlib::install_deflate_service[install_deflate_service]

cpp:boost::http::zlib::install_inflate_service[install_inflate_service]

cpp:boost::http::zlib::install_zlib_service[install_zlib_service]

| **Constants**

cpp:boost::http::zlib::compression_level[compression_level]

cpp:boost::http::zlib::compression_method[compression_method]

cpp:boost::http::zlib::compression_strategy[compression_strategy]

cpp:boost::http::zlib::data_type[data_type]

cpp:boost::http::zlib::error[error]

cpp:boost::http::zlib::flush[flush]

| **Types**

cpp:boost::http::brotli::decode_service[decode_service]

cpp:boost::http::brotli::decoder_state[decoder_state]

cpp:boost::http::brotli::encode_service[encode_service]

cpp:boost::http::brotli::encoder_state[encoder_state]

**Functions**

cpp:boost::http::brotli::install_decode_service[install_decode_service]

cpp:boost::http::brotli::install_encode_service[install_encode_service]

cpp:boost::http::brotli::install_brotli_service[install_brotli_service]

| **Constants**

cpp:boost::http::brotli::constants[constants]

cpp:boost::http::brotli::decoder_param[decoder_param]

cpp:boost::http::brotli::decoder_result[decoder_result]

cpp:boost::http::brotli::encoder_mode[encoder_mode]

cpp:boost::http::brotli::encoder_operation[encoder_operation]

cpp:boost::http::brotli::encoder_parameter[encoder_parameter]

cpp:boost::http::brotli::error[error]

|===

[width=100%]
|===
2+| *bcrypt* | *JSON*

| **Types**

cpp:boost::http::bcrypt::result[result]

**Functions**

cpp:boost::http::bcrypt::compare[compare]

cpp:boost::http::bcrypt::gen_salt[gen_salt]

cpp:boost::http::bcrypt::get_rounds[get_rounds]

cpp:boost::http::bcrypt::hash[hash]

| **Constants**

cpp:boost::http::bcrypt::error[error]

cpp:boost::http::bcrypt::version[version]

| **Types**

cpp:boost::http::json_sink[json_sink]

|===
