//
// Copyright (c) 2025 Mohammad Nejati
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at https://www.boost.org/LICENSE_1_0.txt)
//
// Official repository: https://github.com/boostorg/url
//


[#reference]
= Reference

[width=100%]
|===
3+| *HTTP* | *RFC*

| *Types (1/2)*

cpp:boost::http::fields[fields]

cpp:boost::http::fields_base[fields_base]

cpp:boost::http::file[file]

cpp:boost::http::file_sink[file_sink]

cpp:boost::http::file_source[file_source]

cpp:boost::http::header_limits[header_limits]

cpp:boost::http::message_base[message_base]

cpp:boost::http::metadata[metadata]

cpp:boost::http::parser[parser]

cpp:boost::http::request[request]

cpp:boost::http::request_base[request_base]

cpp:boost::http::request_parser[request_parser]

cpp:boost::http::response[response]

cpp:boost::http::response_base[response_base]

cpp:boost::http::response_parser[response_parser]

cpp:boost::http::serializer[serializer]

| **Types (2/2)**

cpp:boost::http::sink[sink]

cpp:boost::http::source[source]

cpp:boost::http::static_request[static_request]

cpp:boost::http::static_response[static_response]

cpp:boost::http::string_body[string_body]

**Functions**

cpp:boost::http::combine_field_values[combine_field_values]

cpp:boost::http::install_parser_service[install_parser_service]

cpp:boost::http::install_serializer_service[install_serializer_service]

cpp:boost::http::int_to_status[int_to_status]

cpp:boost::http::obsolete_reason[obsolete_reason]

cpp:boost::http::string_to_field[string_to_field]

cpp:boost::http::string_to_method[string_to_method]

cpp:boost::http::to_status_class[to_status_class]

cpp:boost::http::to_string[to_string]

// cpp:boost::http::operator<<[operator<<]

| **Constants**

cpp:boost::http::condition[condition]

cpp:boost::http::content_coding[content_coding]

cpp:boost::http::error[error]

cpp:boost::http::field[field]

cpp:boost::http::file_mode[file_mode]

cpp:boost::http::method[method]

cpp:boost::http::payload[payload]

cpp:boost::http::status[status]

cpp:boost::http::status_class[status_class]

cpp:boost::http::version[version]

**Type Traits**

cpp:boost::http::is_sink[is_sink]

cpp:boost::http::is_source[is_source]

| **Grammar**

cpp:boost::http::parameter_rule[parameter_rule]

cpp:boost::http::quoted_token_rule[quoted_token_rule]

cpp:boost::http::token_rule[token_rule]

cpp:boost::http::upgrade_protocol_rule[upgrade_protocol_rule]

cpp:boost::http::upgrade_rule[upgrade_rule]

**Types**

cpp:boost::http::upgrade_protocol[upgrade_protocol]

cpp:boost::http::parameter[parameter]

cpp:boost::http::quoted_token_view[quoted_token_view]

**Functions**

cpp:boost::http::list_rule[list_rule]

**Constants**

cpp:boost::http::tchars[tchars]

|===
